apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: seckou-dev
data:
  nginx.conf: |
    server {
        listen 8080;
        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
  app.js: |
    const express = require('express');
    const mysql = require('mysql2');
    const app = express();
    const db = mysql.createConnection({
      host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DB_NAME
    });
    app.get('/', (req, res) => {
      db.query('SELECT "MySQL VM2 - TP OpenShift OK" as msg', (err, results) => {
        if (err) return res.status(500).send('Erreur DB: ' + err.message);
        res.send('<h1>' + results[0].msg + '</h1>');
      });
    });
    app.listen(3000, () => console.log('Ready'));
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: seckou-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
        - name: nodejs-app
          image: image-registry.openshift-image-registry.svc:5000/openshift/nodejs:18-ubi8
          command: ["sh", "-c", "echo \"$APP_JS\" > app.js && node app.js"]
          env:
            - name: DB_HOST
              value: "vm2-mysql-service"
            - name: DB_USER
              value: "appuser"
            - name: DB_PASSWORD
              value: "AppPass123!"
            - name: DB_NAME
              value: "appdb"
            - name: APP_JS
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: app.js
        - name: nginx
          image: bitnami/nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-config
              mountPath: /opt/bitnami/nginx/conf/server_blocks/my_server.conf
              subPath: nginx.conf
      volumes:
        - name: app-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  namespace: seckou-dev
spec:
  selector:
    app: nginx-web
  ports:
    - name: http
      port: 80
      targetPort: 8080